language: ruby
rvm:
- 2.0.0
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: X3aFSAGbgpVDe7kL8EhuEULGkfm75cbixARpom0Q34B1rRPt/B12YPEQx6UhbICYjliJVUJREgBeOks36XYqevKOrA9SCZEl3AyvZTU6TTWRc9cPO6b0cGoJlfCIMmaL68O2G8Ck4J4vw+sfVHEe1a1qJ/1u/otkoA2NmIgso2o=
  app: bibb
  on:
    repo: LosGonas/bibber
  strategy: git
