require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RefencesController do

  # This should return the minimal set of attributes required to create a valid
  # Refence. As you add validations to Refence, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RefencesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all refences as @refences" do
      refence = Refence.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:refences)).to eq([refence])
    end
  end

  describe "GET show" do
    it "assigns the requested refence as @refence" do
      refence = Refence.create! valid_attributes
      get :show, {:id => refence.to_param}, valid_session
      expect(assigns(:refence)).to eq(refence)
    end
  end

  describe "GET new" do
    it "assigns a new refence as @refence" do
      get :new, {}, valid_session
      expect(assigns(:refence)).to be_a_new(Refence)
    end
  end

  describe "GET edit" do
    it "assigns the requested refence as @refence" do
      refence = Refence.create! valid_attributes
      get :edit, {:id => refence.to_param}, valid_session
      expect(assigns(:refence)).to eq(refence)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Refence" do
        expect {
          post :create, {:refence => valid_attributes}, valid_session
        }.to change(Refence, :count).by(1)
      end

      it "assigns a newly created refence as @refence" do
        post :create, {:refence => valid_attributes}, valid_session
        expect(assigns(:refence)).to be_a(Refence)
        expect(assigns(:refence)).to be_persisted
      end

      it "redirects to the created refence" do
        post :create, {:refence => valid_attributes}, valid_session
        expect(response).to redirect_to(Refence.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved refence as @refence" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Refence).to receive(:save).and_return(false)
        post :create, {:refence => {  }}, valid_session
        expect(assigns(:refence)).to be_a_new(Refence)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Refence).to receive(:save).and_return(false)
        post :create, {:refence => {  }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested refence" do
        refence = Refence.create! valid_attributes
        # Assuming there are no other refences in the database, this
        # specifies that the Refence created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Refence).to receive(:update).with({ "these" => "params" })
        put :update, {:id => refence.to_param, :refence => { "these" => "params" }}, valid_session
      end

      it "assigns the requested refence as @refence" do
        refence = Refence.create! valid_attributes
        put :update, {:id => refence.to_param, :refence => valid_attributes}, valid_session
        expect(assigns(:refence)).to eq(refence)
      end

      it "redirects to the refence" do
        refence = Refence.create! valid_attributes
        put :update, {:id => refence.to_param, :refence => valid_attributes}, valid_session
        expect(response).to redirect_to(refence)
      end
    end

    describe "with invalid params" do
      it "assigns the refence as @refence" do
        refence = Refence.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Refence).to receive(:save).and_return(false)
        put :update, {:id => refence.to_param, :refence => {  }}, valid_session
        expect(assigns(:refence)).to eq(refence)
      end

      it "re-renders the 'edit' template" do
        refence = Refence.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Refence).to receive(:save).and_return(false)
        put :update, {:id => refence.to_param, :refence => {  }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested refence" do
      refence = Refence.create! valid_attributes
      expect {
        delete :destroy, {:id => refence.to_param}, valid_session
      }.to change(Refence, :count).by(-1)
    end

    it "redirects to the refences list" do
      refence = Refence.create! valid_attributes
      delete :destroy, {:id => refence.to_param}, valid_session
      expect(response).to redirect_to(refences_url)
    end
  end

end
